language: android

before_install:
 - rm -f gradle.properties
 - cp gradle.properties.example gradle.properties
 - chmod +x gradlew

android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - platform-tools
    - extra-android-m2repository

jdk:
    - oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

script:
    ./gradlew assembleDebug --stacktrace
